### ISSUE TITLE
Fails on Fedora 38

### ISSUE THREAD

**Issue by melissaboiko** [aruhier/ansible-role-unbound#24]
My configuration was working fine on Debian, but on Fedora the `unbound-checkconf` stage fails with the message:

> /etc/unbound/trusted-key.key: No such file or directory

There is indeed no trusted-key.key on a fresh Fedora install with unbound from the package manager.

I'm guessing this is from Ansible var `unbound_trust_anchor_file:` which is set on `vars/RedHat.yml`, and blank on `Debian.yml`.

**Comment by aruhier** [comment]
Thanks for the bug report!
I added Fedora in my Molecule tests, and fixed the `trust_anchor` config.
