### ISSUE TITLE
Cannot reload service when control is disabled

### ISSUE THREAD

**Issue by dmaes** [aruhier/ansible-role-unbound#5]
Reloading the unbound service fails when control is disabled. Since this is disabled by default, the `restart unbound` handler will fail when using the default config. Default behavior should be to either restart the service or restart when reload fails. Making restart/reload conditional based on `unbound_control_enable` will still fail when changing control from disabled to enabled.

(On debian buster)

**Comment by aruhier** [comment]
Hello,
Thanks for the bug report. I don't understand, can you give more details about the error you're getting?

I don't understand why unbound would fail to start if the control feature is disabled.

**Comment by dmaes** [comment]
Starting and stopping (ansible `service: state=started/stopped/restarted` == `systemctl start/stop/restart` on systemd machines) the unbound service works fine with the control disabled. Reloading (ansible `service: state=reloaded` == `systemctl reload` on systemd machines) the service fails when the control feature is disabled.
The systemd `ExecReload` function runs `/usr/sbin/unbound-control reload` (at least, on debian 10), which fails when control is disabled.
Your `restart unbound` handler defaults to `service: state=reloaded`, which triggers `systemctl reload`, which executes `/usr/sbin/unbound-control reload`, which fails when the unbound control feature is disabled. So your handler should either default to `service: state=restarted`, try `service: state=reloaded` and fallback to `service: state=restarted` if `service: state=reloaded` fails or check if the control feature is enabled at the beginning of your role and chose restarted/reloaded based on that (this would be the best solution IMO)

**Comment by aruhier** [comment]
Oh ok I see. Thanks for the explanation, I'll push a fix for that!

**Comment by aruhier** [comment]
Can you test the branch `fix_reload` please?

**Comment by dmaes** [comment]
Took a look at it, should work fine except when the very first time you run it after you set `unbound_control_enable` to `yes` (first time ever to run role, or when changing from `no` to `yes`). Unbound control will only be enabled after the actual reload/restart, so that needs to be a restart, not a reload.

I would suggest doing something like this at the start (before all other tasks):
```yaml
- name: Get current state via unbound control
  become: yes
  command: unbound-control status
  register: _unbound_status
  changed_when: false
  failed_when: false
```
and then do this:
```yaml
unbound_reloaded_state: "{{ 'reloaded' if (unbound_control_enable == 'yes' and _unbound_status.rc == 0) else 'restarted' }}"
```

**Comment by aruhier** [comment]
That's a nice catch, thanks! Yeah indeed I completely forgot about that.

I'm going to use the `unbound-control status`, thanks!

**Comment by aruhier** [comment]
@dmaes: I updated my change, can you confirm it works correctly?

**Comment by dmaes** [comment]
Still does not work correctly:
1) You have to run it before the `Set OS specific vars if undefined` task, otherwise the result will always be `restarted` because `_unbound_status` is not yet defined when you define `unbound_reloaded_state`
2) `_unbound_status` is a dict, so it will always eval to `true` when used in a conditional. So you must use the return code of the command in your conditional (`'reloaded' if _unbound_status.rc == 0`)
3) You must use both `_unbound_status.rc == 0` and `unbound_control_enable == 'yes'`) because disabling unbound control, even when currently enabled and thus `_unbound_status.rc == 0`, will result in a failed reload.

**Comment by aruhier** [comment]
> Still does not work correctly:
> 
>     1. You have to run it before the `Set OS specific vars if undefined` task, otherwise the result will always be `restarted` because `_unbound_status` is not yet defined when you define `unbound_reloaded_state`
> 
>     2. `_unbound_status` is a dict, so it will always eval to `true` when used in a conditional. So you must use the return code of the command in your conditional (`'reloaded' if _unbound_status.rc == 0`)
> 
>     3. You must use both `_unbound_status.rc == 0` and `unbound_control_enable == 'yes'`) because disabling unbound control, even when currently enabled and thus `_unbound_status.rc == 0`, will result in a failed reload.

Indeed, I fixed all your points. Thanks!

**Comment by dmaes** [comment]
Seems to work now

**Comment by aruhier** [comment]
Thanks!
